import type { MetadataRoute } from "next";

// Installable PWA: standalone window, no native app. Icons are generated by
// the /icons/[size] route so there are no binary assets to keep in sync.
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Clockwise",
    short_name: "Clockwise",
    description: "One trip. Many clocks.",
    start_url: "/",
    scope: "/",
    display: "standalone",
    background_color: "#f7f8f6",
    theme_color: "#163a2c",
    icons: [
      { src: "/icons/192", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icons/512", sizes: "512x512", type: "image/png", purpose: "any" },
      { src: "/icons/512", sizes: "512x512", type: "image/png", purpose: "maskable" },
    ],
  };
}
